name: daily-cron
on:
  schedule:
    - cron: '* 1 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://daily-leetcode-push.vercel.app/daily' \
          --header 'Authorization: Bearer ${{ secrets.DING_TOKEN }}'